### ISSUE TITLE
Graph view doesn't work

### ISSUE THREAD

**Issue by elsaperdrix** [openfisca/legislation-explorer#18]
[Graph view](https://legislation.openfisca.fr/graph/) doesn't work.

**Comment by benjello** [comment]
Please welcome @elsaperdrix which is a newcomer from IPP !
She will work on dependance.

**Comment by pnbt** [comment]
Hi @elsaperdrix, I'll look into that tomorrow morning.

Cheers!

Le 27 sept. 2016 19:42, "Mahdi Ben Jelloul" <notifications@github.com> a
écrit :

Please welcome @elsaperdrix <https://github.com/elsaperdrix> which is a
newcomer from IPP !
She will work on dependance.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/openfisca/legislation-explorer/issues/18#issuecomment-249940833>,
or mute the thread

**Comment by pnbt** [comment]
The error is simple and due to the new HTTPS settings. I don't have the rights to push, there are several ways to solve it but I don't know which one Christophe prefers, so if it's not too urgent I would wait for @cbenz on monday, otherwise I can see with Emmanuel today. Let me know!

**Comment by cbenz** [comment]
Fixed!

For the record it was not an HTTPS related problem but an internal server error which produced nothing in the logs. I restarted openfisca-web-api on the server and it's OK.

Thanks @elsaperdrix
