### ISSUE TITLE
Display information from latest published package

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#24]
The data source should be the latest available version of OpenFisca on PyPI.

**Comment by MattiSG** [comment]
Use the official `api.openfisca.fr` instance, if it breaks the UI then deploy the UI on an independent version.

**Comment by MattiSG** [comment]
Elaborates on #26.

**Comment by cbenz** [comment]
This implies some sysadmin on the server hosting https://legislation.openfisca.fr/.

The [auto-update-pip-packages](https://github.com/openfisca/openfisca-ops/tree/master/auto-update-pip-packages script was already written by me, cf https://github.com/openfisca/openfisca-ops

**Comment by cbenz** [comment]
The script is restablished on the server now via a cron job.

Emails are sent to the `webmaster@openfisca.fr` alias, only if an update is performed.

**Comment by cbenz** [comment]
Can @fpagnoux double-check that https://legislation.openfisca.fr/ displays information corresponding to the latest release? Thanks!

**Comment by cbenz** [comment]
For the record, the email sent contains this kind of content:

```
- New version of package OpenFisca-France was found on PyPI: current=4.1.7, new=12.0.4
- New version of package OpenFisca-Web-API was found on PyPI: current=2.0.0, new=3.0.0
- New version(s) of PyPI package(s) were found and installed. Restarting openfisca-web-api.service and legislation-explorer.service as a consequence.
- Triggering an HTTP request on https://api.openfisca.fr/ to pre-load OpenFisca-Web-API simulation results, so the first user will not have to wait. Response body:
{"apiVersion": 1, "message": "Welcome, this is OpenFisca Web API.", "method": "/"}
```

**Comment by fpagnoux** [comment]
Where should I double check ? On a local instance or on https://legislation.openfisca.fr/ ?

**Comment by fpagnoux** [comment]
Yep, you can see it in the [JSON objects returned by the api](https://api.openfisca.fr/api/1/variables?name=csg).
```json
{
"apiVersion": 1,
"country_package_name": "openfisca_france",
"country_package_version": "12.0.4"
```

**Comment by fpagnoux** [comment]
Is it really relevant to watch the wep api package ? 

We want to make sure we always have the latest version of the legislation, but I have trouble seeing the interest of automatically ugrade the web api. What would happen if we publish a new version of the api that is not yet compatible with the master of france ?

**Comment by MattiSG** [comment]
Also, the procedure for auto-updating should at least be documented, or even better scripted, so that other instances (such as Tunisia) are also always up-to-date 🙂

**Comment by cbenz** [comment]
@MattiSG The procedure is documented on https://github.com/openfisca/openfisca-ops/tree/master/auto-update-pip-packages and it is scripted ^^

**Comment by cbenz** [comment]
> Is it really relevant to watch the wep api package ?

Yes, because:

OpenFisca-Web-API [depends on OpenFisca-Core](https://github.com/openfisca/openfisca-web-api/blob/d790243123c72fd198cc29a63d6dd4dedb316510/setup.py#L59) with version constraints, so if the auto-update updates only France and Core, the installed version of Web-API could be out-of-sync with these versions. This leads to a `ConstraintError` exception at the next restart, which we want to avoid.

(After an update of Core and France, the Web-API must be restarted otherwise it will serve the in-memory version of those packages.)

> What would happen if we publish a new version of the api that is not yet compatible with the master of france ?

I think that if we specify a set of packages on the same `pip install` command line, pip selects for each of them a version mutually compatible with the others. It isn't obviously the latest version.

For example, given:
- Core was published with versions 1.0.0, 2.0.0 and 3.0.0
- France version 12.0.0 requires `Core >= 2.0.0, < 3.0.0`
- Web-API
  - version 1.0.0 requires `Core >= 1.0.0, < 2.0.0`
  - version 2.0.0 requires `Core >= 2.0.0, < 3.0.0`
  - version 3.0.0 requires `Core >= 3.0.0, < 4.0.0`

then `pip install OpenFisca-Core OpenFisca-France OpenFisca-Web-API` selects:
- Core 2.0.0
- France 12.0.0
- Web-API 2.0.0

> The Web-API, even if published with version 3.0.0, does not satisfies the constraints, so it's not selected.

This is a good question and I'm not sure pip behaves really like that since I don't master pip enough, and I don't remember having read anything about that in the docs. And I remember having read many issues about the constraint solver of pip (when other package managers use external constraint solvers proven for their efficiency).

I can test it in a dummy environment thanks to the [testpypi](https://testpypi.python.org/pypi) repo.

**Comment by fpagnoux** [comment]
I think we need to clear the dependencies between `france` and `web-api`. 
While there is not pure dependencies between these two, it is clear that the `france` country package can only be served with certain version of the `api`. @MattiSG, is that a _peer dependency_ ?

I don't think pip handle peer dependencies anyway. What I did with `senegal` was to add an extra optional dependency towards the api. This way you could do:
```sh
pip install openfisca-france
```
to just get the country package, or
```sh
pip install openfisca-france[api]
```
to install both the country package and the right version that is able to serve it.

What do you think about this solution ?

**Comment by cbenz** [comment]
I think this is not related to this issue, can we switch to another one on OpenFisca-Web-API?

I don't think it's a peer dependency. A peer dependency is there to express the dependency between a package P (like a plugin) towards a package L (like a library), but neither P or L is useful in itself. Both of them can be a dependency of an application A.

So:
```
P =(peer-depends on )=> L
A =(depends on)=> P
A =(depends on)=> L
```

But I think that npm peer dependencies were introduced because of the tree structure of the `node_modules` directory, in order to avoid having duplicate installations of L (cf my previous example).

Now that npm uses a flat structure for `node_modules`, the peer dependencies is not relevant anymore, I think.

So in OpenFisca with pip, I think that indeed the Web-API does not depends on France.

> `pip install openfisca-france[api]`

I'm not satisfied with this solution actually. France should not know about the API.

With pip the idiom is to use a `requirements.txt` file to describe the virtualenv you'd like to deploy.

**Comment by MattiSG** [comment]
> it is clear that the france country package can only be served with certain version of the web-api

Why?

If it's just because of the transitive dependency `api` → `parser` → `core` and the actual dependency `france` → `core`, I would tend to hope that stabilising the `core` API will also stabilise the `parser`, and that it will sort itself out over time.

I like the simplicity of `pip install openfisca-france[api]`, but I dislike referencing the API in a package that can be used without it. What if the API evolves to fix a critical security issue? Do we need to also publish a new `france` version to reflect it?

As for whether it is a peer dependency or not, I would tend to think it is one, at least based on [Domenic's presentation](https://nodejs.org/en/blog/npm/peer-dependencies/). I don't think there's a condition of “uselessness” of both packages, only of a version compatibility range with another package that is necessary for the package to run, yet no direct dependency.

**Comment by MattiSG** [comment]
Ok, so if this is scripted, documented and in place, I think this can be considered done! Good job @cbenz!  :)

**Comment by fpagnoux** [comment]
> > it is clear that the france country package can only be served with certain version of the web-api
> 
> Why?
> 
> If it's just because of the transitive dependency `api` → `parser` → `core` and the actual dependency `france` → `core`, I would tend to hope that stabilising the `core` API will also stabilise the `parser`, and that it will sort itself out over time.
> 

Not only:
*  we also have `api` -> `core` directly (not sure why).
* the country package, such as `france`, must expose some methods / class to be served with the api. For instance, [when the api loads its environment](https://github.com/openfisca/openfisca-web-api/blob/master/openfisca_web_api/environment.py#L103), there must be a `CountryTaxBenefitSystem` class exposed by the package for the api to work. This is a convention that will probably not evolve anymore, but there is still some kind of dependency.
