### ISSUE TITLE
Duplicate parameters in list

### ISSUE THREAD

**Issue by benjello** [openfisca/legislation-explorer#29]
Look for CSG on the [parameters page](https://legislation.openfisca.fr/parameters) and you will see what I mean. (Might be related to https://github.com/openfisca/openfisca-core/pull/436).

**Comment by MattiSG** [comment]
Please, try to be specific when you open an issue. This is not actionable  ;)

The issue seems to be duplicate parameters appearing in the list, as shown in this screenshot:

![capture d ecran 2017-01-26 a 09 25 15](https://cloud.githubusercontent.com/assets/222463/22324402/6b7015b2-e3a9-11e6-9576-55a6dbafb4f8.png)

**Comment by MattiSG** [comment]
It seems that each period change generates a new parameter in the list, as each of them comprises only two period-value pairs.

**Comment by benjello** [comment]
Some parameters seems duplicated and some are completely empty.

![screenshot from 2017-01-26 09-31-29](https://cloud.githubusercontent.com/assets/1175927/22324572/74a2fc84-e3aa-11e6-9dd7-9b76544dc24d.png)

Actually, I would think that those who seem duplicated are actually the parent node of empty children nodes.

**Comment by cbenz** [comment]
@benjello I don't think it's related to https://github.com/openfisca/openfisca-core/pull/436 since this PR is not merged ;-)

I think it's a bug somewhere in [`parameters.jsx`](https://github.com/openfisca/legislation-explorer/blob/master/src/components/pages/parameters.jsx).

**Comment by cbenz** [comment]
Fixed through #40
